import Head from 'next/head'
import { Inter } from '@next/font/google'
import AddedList from '../Components/AddedList'
import { useEffect, useState } from 'react'
import { MILESTONE } from '../url'
import { toastFunction } from '../Components/Toast'
const inter = Inter({ subsets: ['latin'] })
const axios = require('axios');

export default function Home() {
  //this state will help to fetch the data again after saving any data 
  const [dataSave, setDataSave] = useState(0)
  const [milestone, setMilestone] = useState([])
  // error handling state 
  const [isError, setIsError] = useState("")
  //this function will give the milestone
  const getData = async () => {
    try {
      const response = await axios.get(MILESTONE)
      setMilestone(response.data)
    }
    catch (error) {
      setIsError(error.message)
    }

  }


  useEffect(() => {
    setIsError("")
    getData()
  }, [dataSave])

  const handleSubmit = (event) => {

    event.preventDefault()
    const goal = event.target.text.value;
    const time = event.target.time.value;

    // validate that goal and time both is sated 
    if (goal === '' || goal === undefined || time === '' || time === undefined) {
      toastFunction('error', 'Sorry you have to set both GOAL and TIME')
      return
    }

    const body = { todo: goal, time: time, listingNo: milestone.length + 1 }

    axios.post('http://localhost:5000/milestone', body)
      .then(function (response) {
        console.log(response);
        if (response.data.acknowledged === true) {
          toastFunction('success', 'Successfully Added')
          setDataSave(dataSave + 1)
        }

      })
      .catch(function (error) {
        console.log(error);
      });
    setGoalLength(0)
    event.target.reset()

  }

  const [goalLength, setGoalLength] = useState(0)
  // this function will validate input section that user have to set a goal under limited word
  const goalInputSection = (event) => {
    event.preventDefault()
    const goal = event.target.value;
    setGoalLength(goal.length)
  }


  return (
    <>

      <Head>
        <title>Practice CRUD operation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-4/5 mx-auto p-8'>
        <p className='text-2xl font-bold text-slate-400 text-center mt-5 uppercase bg-lime-200 w-4/6 mx-auto px-4 py-2 rounded-lg shadow-md shadow-yellow-100'>TODO LIST</p>
        <div className='w-3/6 p-5 rounded-lg bg-lime-200 mx-auto shadow-2xl shadow-gray-300 flex-col mt-8 flex justify-center items-center'>
          <form onSubmit={handleSubmit} className='relative w-full flex flex-col justify-center items-center gap-2'>
            <p className={`absolute top-2 right-24 ${goalLength === 0 && 'text-gray-400'} ${goalLength > 0 && goalLength < 30 && 'text-green-500'} ${goalLength === 30 && 'text-red-500'}  text-sm`}>{goalLength}/30</p>
            <input type="text" name="text" onChange={goalInputSection} maxLength="30" id="text" className='w-4/6 rounded-lg px-5 py-2 outline-none' placeholder='Enter your goal' />
            <input type="time" name="time" id="time" className='w-4/6 rounded-lg px-5 py-2 outline-none' placeholder='Enter time' />
            <button type='submit' className='px-10 py-2 rounded bg-orange-400 hover:bg-orange-500 duration-300 text-white mt-4'>Add</button>
          </form>
        </div>
        <div>
          {
            isError !== '' && <p className='text-center mt-3 text-xl text-red-500'>{isError}</p>
          }
        </div>
        {
          milestone.length > 0 && <AddedList data={milestone} setDataSave={setDataSave} />
        }
      </main>

    </>
  )
}
